services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 